obj-m += rcio_core.o 
obj-m += rcio_spi.o
rcio_spi-objs := src/rcio_spi.o
rcio_core-objs := src/rcio_core.o src/rcio_adc.o src/rcio_pwm.o src/rcio_rcin.o src/rcio_status.o src/rcio_safety.o src/rcio_gpio.o

ccflags-y := -std=gnu99

